@extends('layouts.app')
@section('content')
@include('partials.page-hero', ['eyebrow' => __('site.contact.eyebrow'), 'title' => __('site.contact.title'), 'lead' => __('site.contact.lead')])
<x-breadcrumbs :seo="$seo" />
<section class="section contact-section"><div class="container contact-grid"><div class="contact-aside reveal"><p class="eyebrow">{{ __('site.contact.direct_contact') }}</p><h2>Dũng Nguyễn</h2><a href="mailto:nguyendhungdung@gmail.com">nguyendhungdung@gmail.com</a><a href="https://zaloapp.com/qr/p/1ute4cg6xoom2" target="_blank" rel="noopener">Zalo ↗</a><div class="contact-orb"><img src="{{ asset('images/hero/ai-earth-emerald.webp') }}" alt="{{ __('site.home.earth_alt') }}" width="440" height="440" loading="lazy"></div></div>
<div class="contact-form-wrap panel reveal">@if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif
<form method="post" action="{{ route('contact.store', ['locale' => app()->getLocale()]) }}" class="contact-form" data-contact-form>@csrf<input class="honeypot" type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true">
<div class="form-grid"><label><span>{{ __('site.contact.name') }} *</span><input name="name" value="{{ old('name') }}" required maxlength="120">@error('name')<small>{{ $message }}</small>@enderror</label><label><span>{{ __('site.contact.company') }}</span><input name="company" value="{{ old('company') }}" maxlength="160"></label><label><span>{{ __('site.contact.email') }} *</span><input type="email" name="email" value="{{ old('email') }}" required maxlength="190">@error('email')<small>{{ $message }}</small>@enderror</label><label><span>{{ __('site.contact.phone') }}</span><input name="phone" value="{{ old('phone') }}" maxlength="40"></label>
<label><span>{{ __('site.contact.need') }} *</span><select name="need" required><option value="">—</option>@foreach(__('site.contact.needs') as $value=>$label)<option value="{{ $value }}" @selected(old('need')===$value)>{{ $label }}</option>@endforeach</select></label><label><span>{{ __('site.contact.budget') }}</span><select name="budget"><option value="">—</option>@foreach(__('site.contact.budgets') as $value=>$label)<option value="{{ $value }}" @selected(old('budget')===$value)>{{ $label }}</option>@endforeach</select></label><label><span>{{ __('site.contact.timeline') }}</span><select name="timeline"><option value="">—</option>@foreach(__('site.contact.timelines') as $value=>$label)<option value="{{ $value }}" @selected(old('timeline')===$value)>{{ $label }}</option>@endforeach</select></label></div>
<label><span>{{ __('site.contact.message') }} *</span><textarea name="message" rows="7" required minlength="20" maxlength="5000">{{ old('message') }}</textarea>@error('message')<small>{{ $message }}</small>@enderror</label><div class="form-submit"><p>{{ __('site.contact.privacy') }}</p><button class="button button-primary" type="submit">{{ __('site.contact.send') }} <span>→</span></button></div></form></div></div></section>
@endsection
